name: node
on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '**.lock'
    branches:
      - master
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '**.lock'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint --fix

      - name: Check for uncommitted changes
        run: |
          git add .
          git diff --staged --exit-code

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install

      - name: Bundle JavaScript
        run: yarn build
